name: 'GithubActions-Terraform'

on:
  push:
    branches:
      - "main"

jobs:
  apply-tf:
    name: Terraform apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: set ROLE
      run: |
        echo "AWS_ROLE_ARN=${{secrets.AWS_ROLE_ARN}}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3

    - name: cofigure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       role-to-assume: ${{secrets.AWS_ROLE_ARN}}
       aws-region: ap-northeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.2.0

    - name: Terraform Init
      run: terraform init
      working-directory: terrasform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
